---
- name: Apply post install configurations
  hosts: pve1
  gather_facts: false
  any_errors_fatal: true
  tasks:
    - name: Install NFS Server
      ansible.builtin.apt:
        name: nfs-kernel-server
        state: present
        update_cache: true

    - name: Append post-up command to iface eno1 inet manual
      ansible.builtin.lineinfile:
        path: /etc/network/interfaces
        insertafter: "^iface eno1 inet manual"
        line: "        post-up ethtool -K eno1 tso off gso off"
        state: present
      notify: Restart networking

  handlers:
    - name: Restart networking
      ansible.builtin.service:
        name: networking
        state: restarted
        enabled: yes
